name: smart_health_tracker
description: A Smart Health Tracker Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (optional - for login, data sync)
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.2.1

   # Permissions
  permission_handler: ^11.3.0

  # Health & UI & Sensors
  pedometer: ^4.0.1
  heart_bpm: ^2.0.0+0
  camera: ^0.10.5+2
  tflite_flutter: ^0.9.0
  provider: ^6.1.2
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2 # To save water intake persistently

  fl_chart: ^0.66.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2


  intl: ^0.19.0

  # Flutter essentials
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Optional if you want to use custom images later
  assets:
    - assets/images/
